### ISSUE TITLE
美玉姨似乎有個bug

### ISSUE THREAD

**Issue by jus122** [CarolHsu/rumors-api-client#13]
有朋友的朋友在line群組裡貼了臉書自家農產品黑米糙米的圖跟文  美玉姨回覆了同婚專法的闢謠文  是否能查看一下bug的發源處  謝謝🙏

這是臉書文的連結（供測試）：
https://m.facebook.com/story.php?story_fbid=1544325712367164&id=100003692494187

**Comment by CarolHsu** [comment]
我注意到了，因為我省略了比對 querystring for url, will fix!

**Comment by jus122** [comment]
不會  辛苦了   感謝有妳❤️😊
