### ISSUE TITLE
👏👏 很棒的專案，幾個小建議

### ISSUE THREAD

**Issue by yutin1987** [CarolHsu/rumors-api-client#3]
1. readme.md 中的 `Contributing` 與 `Code of Conduct` 似乎屬重複的內容
2. 建議使用 md 補上隱私權條款，由於加入『群』中會取得所有的對話紀錄

**Comment by CarolHsu** [comment]
好的 👍 
Will do, 將在 http://github.com/carolhsu/rumor-checker 增加條款。

**Comment by CarolHsu** [comment]
out of this gem's responsibility. will implement in repo http://github.com/carolhsu/rumor-checker

**Comment by nekojean** [comment]
請問可以讓美玉姨不要每次有人加入群組就觸發打招呼語嗎？
這樣會被其他人反感，特別是群的主揪。

**Comment by CarolHsu** [comment]
hi @nekojean 因為希望所有人都是知情同意的狀況下，讓新加入的成員在一開始就可以知道美玉姨的存在好像是必須的。讓這個功能消失是很簡單，不過前提是有更好的替代方案（例如文案可以改成怎麼樣讓主揪不被討厭，也達成所有人知情同意的目的，或是其他~）

**Comment by nekojean** [comment]
謝謝您的回覆，不過美玉姨的第一次加入的自我介紹很合理。
但在一個3百多人的群裡，時常有新友加入，
也一直觸發美玉姨連續的自我介紹，真的是干擾。
這樣反而美玉姨取名為 「求證機器人」之類的非一般人名，
還更容易被接受。

**Comment by CarolHsu** [comment]
@nekojean 好的，雖然還沒有正式的 timetable 不過在完成 Google analytics 的設定之後我會 fork 出幾個不同的版本，發佈在美玉姨的 line 個人 timeline 上，讓大家可以自由加入例如像 謠言查證機器人 之類的別的 line bot 帳號
