### ISSUE TITLE
Double quotes in GraphQL request is causing GraphQL parse error

### ISSUE THREAD

**Issue by MrOrz** [CarolHsu/rumors-api-client#4]
In error log of Cofacts API server, we found this:

```
[PARSE ERROR] { ListArticles( filter: { moreLikeThis: { like: "各位:當使用提欵機的時候,為免有人預裝了"盗取密碼"的程式,在揷入你的信用卡前,先按"取消"鍵兩次,這樣做的話,先前的預装程式就會被取消了,你的密碼亦避免了被人窃取。請維持這種習慣:每次揷卡前,先按"取消"鍵兩次。這是銀行業人士的忠告,很有用。請轉告其他你關心的親友們。" } } orderBy: [{ _score: DESC }] first: 4 ) { edges { node { id text } } } }
```

Unfortunately, this specific rumor is requested hundreds of times a day:
<img width="782" alt="2018-12-26 10 55 45" src="https://user-images.githubusercontent.com/108608/50430075-ddf34800-08fc-11e9-90c8-00206c749dd5.png">

It seems that the `"` inside the search string is causing syntax errors. There are a lot of similar queries like this:

<img width="1114" alt="2018-12-26 10 58 53" src="https://user-images.githubusercontent.com/108608/50430344-4a227b80-08fe-11e9-8f00-abfa7312c8d5.png">

Under current implementation it is possible for users to perform GraphQL injection. It should be addressed for the sake of usability and security.

Proposed fix:
Use [GraphQL variables](https://graphql.org/learn/queries/#variables) instead of manual string concatenation

**Comment by CarolHsu** [comment]
good catch! will fix asap 🙏

**Comment by MrOrz** [comment]
Thanks for taking care of this!

A quick note regarding the direction of the fix: use `{query: '...graphql query...', variables: {...variables...}}` in the payload. GraphQL server will handle the passed query and variables.

Inspecting how graphql playground interacts with GraphQL server gives a good example of how to pass variables to the server.
<img width="1379" alt="2018-12-27 1 38 15" src="https://user-images.githubusercontent.com/108608/50467177-b1166200-09dc-11e9-96e7-dca2db8374b1.png">

**Comment by CarolHsu** [comment]
fixed
