### ISSUE TITLE
Search for article and get their replies in one go

### ISSUE THREAD

**Issue by MrOrz** [CarolHsu/rumors-api-client#7]
Currently "search for article using text" and "get the reply using article ID" are separate steps.

Actually it's possible to combine the two queries into one:

<img width="1381" alt="2018-12-28 2 28 06" src="https://user-images.githubusercontent.com/108608/50505138-fb671400-0aac-11e9-83f2-af0d8421cc7a.png">

Hope this helps simplifying the implementation :)

**Comment by MrOrz** [comment]
Another thing is that, 80% similarity can be achieved by supplying `minimimShouldMatch`:

<img width="1382" alt="2018-12-28 2 33 56" src="https://user-images.githubusercontent.com/108608/50505284-b98a9d80-0aad-11e9-8c7b-d866681a5109.png">

Sorry that we did not provide enough documentation on the parameter. The param will be passed to more_like_this query, thus the format matches [its official doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html).

**Comment by CarolHsu** [comment]
significantly helpful information, I will improve it when I got any chance. I deeply agree reduce the requests to confacts database is most important thing to do, will tag high prio for this issue. Thanks for pointing out 👍

**Comment by MrOrz** [comment]
Haha actually the server load on Cofacts side is ok. I think we can manage 3x of the current audiences for now, since the short-message filter is in-place and the server load has dropped significantly. Even in the most busy day (Dec. 25) the service is still running with decent responsiveness.

![cofacts](https://user-images.githubusercontent.com/108608/50518767-60912880-0af2-11e9-9934-50a852ca9052.png)
Actually the server is just running on a single 4GB-ram Linode. I am quite impressed with how the server could handle load.

Actually 2 simple GraphQL queries v.s. 1 nested query has very little difference. I think the latter actually costs more because it will load all replies for all search hits, while the former only loads replies for the most relevant article.

It's just that combining the 2 queries should both reduce the networking overhead between 美玉姨 and Cofacts API, and hopefully can drop the code complexity on 美玉姨's side. After all, using nested queries to fetch all data you want at once is the most prominent benefit of GraphQL, don't be shy to leverage it :)

**Comment by tomohung** [comment]
@CarolHsu the PR https://github.com/CarolHsu/rumors-api-client/pull/9 tried to merge two queries into one.
I didn't utilize `minimumShouldMatch` because I'm not sure if that works as your expectation. Leave it to you.
@MrOrz thanks for the pro tips!

**Comment by CarolHsu** [comment]
finished
